CREATE TABLE IF NOT EXISTS settings(key TEXT PRIMARY KEY,value TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS workers(id INTEGER PRIMARY KEY,name TEXT NOT NULL,startedAt INTEGER,endedAt INTEGER,mealStarted INTEGER,mealFinished INTEGER DEFAULT 0,mealAck INTEGER DEFAULT 0,restRemaining INTEGER NOT NULL,restRunning INTEGER DEFAULT 0,restLast INTEGER,notice TEXT,noticeAt INTEGER,noticeRead INTEGER DEFAULT 0);
CREATE TABLE IF NOT EXISTS events(id INTEGER PRIMARY KEY AUTOINCREMENT,workerId INTEGER,at INTEGER,text TEXT);
CREATE TABLE IF NOT EXISTS sessions(token TEXT PRIMARY KEY,userId INTEGER,role TEXT,expiresAt INTEGER);
INSERT OR IGNORE INTO settings(key,value) VALUES('shiftHours','8');
INSERT OR IGNORE INTO workers(id,name,restRemaining) VALUES(0,'Ker',3000000);
INSERT OR IGNORE INTO workers(id,name,restRemaining) VALUES(1,'Sanyo',3000000);
