const USERS={Ker:{name:"Ker",role:"worker",password:"FKo2mf3FR",id:0},Sanyo:{name:"Sanyo",role:"worker",password:"LVEzVe93deL",id:1},Admin:{name:"Admin",role:"admin",password:"Amderof33"}};const BREAK=50*60*1000;
async function q(env,sql,args=[]){return env.DB.prepare(sql).bind(...args).run()}async function one(env,sql,args=[]){return env.DB.prepare(sql).bind(...args).first()}async function all(env,sql,args=[]){return env.DB.prepare(sql).bind(...args).all()}
async function init(env){await q(env,`CREATE TABLE IF NOT EXISTS settings(key TEXT PRIMARY KEY,value TEXT NOT NULL)`);await q(env,`CREATE TABLE IF NOT EXISTS workers(id INTEGER PRIMARY KEY,name TEXT NOT NULL,startedAt INTEGER,endedAt INTEGER,mealStarted INTEGER,mealFinished INTEGER DEFAULT 0,mealAck INTEGER DEFAULT 0,restRemaining INTEGER NOT NULL,restRunning INTEGER DEFAULT 0,restLast INTEGER,notice TEXT,noticeAt INTEGER,noticeRead INTEGER DEFAULT 0)`);await q(env,`CREATE TABLE IF NOT EXISTS events(id INTEGER PRIMARY KEY AUTOINCREMENT,workerId INTEGER,at INTEGER,text TEXT)`);await q(env,`CREATE TABLE IF NOT EXISTS sessions(token TEXT PRIMARY KEY,userId INTEGER,role TEXT,expiresAt INTEGER)`);for(const [id,name] of [[0,"Ker"],[1,"Sanyo"]]){if(!await one(env,"SELECT id FROM workers WHERE id=?",[id]))await q(env,"INSERT INTO workers(id,name,restRemaining) VALUES(?,?,?)",[id,name,BREAK])}if(!await one(env,"SELECT value FROM settings WHERE key='shiftHours'"))await q(env,"INSERT INTO settings VALUES('shiftHours','8')")}
const ck=req=>req.headers.get("Cookie")?.match(/sc_session=([^;]+)/)?.[1];
async function sess(req,env){let t=ck(req);return t?await one(env,"SELECT userId,role FROM sessions WHERE token=? AND expiresAt>?",[t,Date.now()]):null}
async function log(env,id,text){await q(env,"INSERT INTO events(workerId,at,text) VALUES(?,?,?)",[id,Date.now(),text])}
async function settings(env){return Number((await one(env,"SELECT value FROM settings WHERE key='shiftHours'")).value)}
async function sw(env,id){let s=await one(env,"SELECT * FROM workers WHERE id=?",[id]),e=await all(env,"SELECT at,text FROM events WHERE workerId=? ORDER BY at DESC LIMIT 80",[id]);return {...s,events:e.results,meal:s.mealStarted?{startedAt:s.mealStarted,finished:!!s.mealFinished,ack:!!s.mealAck}:null,notice:s.notice?{text:s.notice,at:s.noticeAt}:null,shiftHours:await settings(env)}}
async function sa(env){let r=await all(env,"SELECT * FROM workers ORDER BY id"),workers=r.results.map(s=>({...s,events:[],meal:s.mealStarted?{startedAt:s.mealStarted,finished:!!s.mealFinished,ack:!!s.mealAck}:null,notice:s.notice?{text:s.notice,at:s.noticeAt}:null}));return {workers,shiftHours:await settings(env)}}
const J=(x,status=200,h={})=>new Response(JSON.stringify(x),{status,headers:{"Content-Type":"application/json",...h}});
export default {async fetch(req,env){await init(env);let p=new URL(req.url).pathname;if(!p.startsWith("/api/"))return env.ASSETS.fetch(req);try{
if(p==="/api/login"&&req.method==="POST"){let {login,password}=await req.json(),u=USERS[login];if(!u||u.password!==password)return J({error:"bad"},401);let token=crypto.randomUUID();await q(env,"INSERT INTO sessions VALUES(?,?,?,?)",[token,u.id??-1,u.role,Date.now()+86400000]);return J({user:{name:u.name,role:u.role,id:u.id},state:u.role==="admin"?await sa(env):await sw(env,u.id)},{headers:{"Set-Cookie":`sc_session=${token}; HttpOnly; Secure; SameSite=Lax; Path=/; Max-Age=86400`}})}
let s=await sess(req,env);if(!s)return J({error:"unauthorized"},401);
if(p==="/api/logout"){await q(env,"DELETE FROM sessions WHERE token=?",[ck(req)]);return J({ok:true},{headers:{"Set-Cookie":"sc_session=; Max-Age=0; Path=/"}})}
if(s.role==="worker"){let id=s.userId;
if(p==="/api/worker/state")return J(await sw(env,id));
if(p==="/api/worker/start"){let w=await one(env,"SELECT startedAt FROM workers WHERE id=?",[id]);if(w.startedAt)return J({error:"Смена уже начата"},409);await q(env,"UPDATE workers SET startedAt=?,endedAt=NULL,mealStarted=NULL,mealFinished=0,mealAck=0,restRemaining=?,restRunning=0,restLast=NULL WHERE id=?",[Date.now(),BREAK,id]);await log(env,id,"Смена начата");return J(await sw(env,id))}
if(p==="/api/worker/end"){let now=Date.now(),w=await one(env,"SELECT * FROM workers WHERE id=?",[id]);let rem=w.restRunning?Math.max(0,w.restRemaining-(now-w.restLast)):w.restRemaining;await q(env,"UPDATE workers SET endedAt=?,restRemaining=?,restRunning=0,restLast=NULL WHERE id=?",[now,rem,id]);await log(env,id,"Смена завершена");return J(await sw(env,id))}
if(p==="/api/worker/meal"){let w=await one(env,"SELECT * FROM workers WHERE id=?",[id]);if(!w.startedAt||w.endedAt||w.mealStarted)return J({error:"Обед недоступен"},409);await q(env,"UPDATE workers SET mealStarted=? WHERE id=?",[Date.now(),id]);await log(env,id,"Начат обеденный перерыв — 50 минут");return J(await sw(env,id))}
if(p==="/api/worker/back"){let w=await one(env,"SELECT * FROM workers WHERE id=?",[id]);if(!w.mealStarted||Date.now()-w.mealStarted<BREAK)return J({error:"Обед ещё не закончился"},409);await q(env,"UPDATE workers SET mealFinished=1,mealAck=1 WHERE id=?",[id]);await log(env,id,"Нажато «Я тут» после обеда");return J(await sw(env,id))}
if(p==="/api/worker/rest-start"){let w=await one(env,"SELECT * FROM workers WHERE id=?",[id]);if(w.restRunning||w.restRemaining<=0)return J({error:"Отдых недоступен"},409);await q(env,"UPDATE workers SET restRunning=1,restLast=? WHERE id=?",[Date.now(),id]);await log(env,id,"Дневной отдых запущен");return J(await sw(env,id))}
if(p==="/api/worker/rest-pause"){let w=await one(env,"SELECT * FROM workers WHERE id=?",[id]);if(!w.restRunning)return J({error:"Отдых не запущен"},409);let rem=Math.max(0,w.restRemaining-(Date.now()-w.restLast));await q(env,"UPDATE workers SET restRemaining=?,restRunning=0,restLast=NULL WHERE id=?",[rem,id]);await log(env,id,"Дневной отдых поставлен на паузу");return J(await sw(env,id))}
}else{if(s.role!=="admin")return J({error:"forbidden"},403);if(p==="/api/admin/state")return J(await sa(env));if(p==="/api/admin/settings"&&req.method==="POST"){let {shiftHours}=await req.json();if(!(shiftHours>=1&&shiftHours<=24))return J({error:"Недопустимое время"},400);await q(env,"UPDATE settings SET value=? WHERE key='shiftHours'",[String(shiftHours)]);return J(await sa(env))}
if(p==="/api/admin/notify"&&req.method==="POST"){let {target,text}=await req.json();if(!text?.trim())return J({error:"Пустое сообщение"},400);let ids=target==="all"? [0,1]:[Number(target)];for(let id of ids){await q(env,"UPDATE workers SET notice=?,noticeAt=?,noticeRead=0 WHERE id=?",[text.trim(),Date.now(),id]);await log(env,id,`Администратор отправил уведомление: «${text.trim()}»`)}return J({ok:true})}}
return J({error:"not found"},404)}catch(e){return J({error:e.message},500)}}};